const imageDomains = [
  'afr.net',
  'assets.blubrry.com',
  'assets.fireside.fm',
  'assets.pippa.io',
  'assets.podomatic.net',
  'atp.fm',
  'cba.fro.at',
  'cdn-images.owltail.com',
  'cdn.changelog.com',
  'content.production.cdn.art19.com',
  'd3wo5wojvuv7l.cloudfront.net',
  'daringfireball.net',
  'dcadata.github.io',
  'elroy.twit.tv',
  'f.prxu.org',
  'files.thisamericanlife.org',
  'fourble.co.uk',
  'geekgabpodcasts.com',
  'i0.wp.com',
  'i1.sndcdn.com',
  'image.ausha.co',
  'image.simplecastcdn.com',
  'images.accessmedia.nz',
  'images.squarespace-cdn.com',
  'images.subsplash.com',
  'itstreaming.apple.com',
  'lexfridman.com',
  'lotemedia.s3.amazonaws.com',
  'media.npr.org',
  'media.redcircle.com',
  'media.wnyc.org',
  'media2.wnyc.org',
  'megaphone.imgix.net',
  'mm.aiircdn.com',
  'mysteriousuniverse.org',
  'noagendaartgenerator.com',
  'noagendaassets.com',
  'noagendachapterart.com',
  'pbcdn1.podbean.com',
  'pod.monster',
  'podcastindex.org',
  'speaking.com',
  'ssl-static.libsyn.com',
  'storage.buzzsprout.com',
  'storage.pinecast.net',
  'thisfilipinoamericanlife.com',
  'upload.wikimedia.org',
  'www.acmeonline.org',
];

if (process.env.NODE_ENV === 'development') {
  imageDomains.push('localhost');
}

module.exports = imageDomains;
